### ISSUE TITLE
3.0.0 polishing

### ISSUE THREAD

**Issue by KennyTV** [ViaVersion/ViaBackwards#179]
A general todo of important stuff:

General
- [x] Configurable item/block/sound mappings as well as their display names***
- [x] Handle new translatables*

Everything from 1.15->1.13
- [x] yes

1.14->1.13.2
- [x] Ghost items drop when another insentient with items in their armorslots dies (no clue on why this happens... yet)

1.13->1.12.2
- [x] Lingering entity particle data
- [x] Face player packet
- [x] Statistics conversion (general category - item/block/entity are won't-fix due to unnecessarily high caching)
- [x] Translatable key changes

The dark side (1.12->1.9)
- [x] General sound check
- [x] Throwable potion data
- [x] Custom block/item mappings*

'*' = probably not too easy 🌂

Be sure to tell us about anything missing :)

**Comment by TNTUP** [comment]
Tested on client 1.12.2 and I've noticed quite "some or less" issues on a PaperSpigot 1.15.2 server.
[Viaver dump](https://dump.viaversion.com/a3fbfe4d621e44315ad5994f091490b58571d29029b338dfc5aafe96ff4cc754)

- Chest facing issues
- Pillagers should be remapped as Illusioners instead of villagers not to mistaken players, ravagers I think could too instead of cows (PS remapped it as a cave spider)
- Skeletons doesn't have their arms raised while aiming at a player
- Explosion (TNT, Creepers etc) doesn't fire up when they blow
- Creative inventory gets scrambled when you press E, when you select your 1.12.2 creative inventory changes the item into 1.13+ item 

Tested on client 1.14.4, no creative inventory issues but no explosion sound persists. I guess it affects all < 1.15.2 versions. Shall I create 3 seperate issues or keep up to date here? 

I'm suspecting that PS is driving me TPS losses, but I have no such way to determine the problem. Not an entity issue.

**Comment by Xernium** [comment]
1. Are you sure you have enabled block-connections in the config?
2. The remaps are debatable, that might see a rework to be a bit less confusing 
3. In which versions?
4. Also in which versions does that happen?
5. Creative mode inventory issues are gotcha and in most cases a known wontfix because creative mode players most of the time don’t send enough data to identify what item was picked as what other item. This is probably related to runtime IDs but other than that there is no packet till even after the fact so that’s not something we can easily help with. It’s the same on ProtocolSupport.     
You may open issue requests for a few of those but some will probably be labeled a wontfix very quickly

**Comment by TNTUP** [comment]
> 1. Are you sure you have enabled block-connections in the config?
> 2. The remaps are debatable, that might see a rework to be a bit less confusing
> 3. In which versions?
> 4. Also in which versions does that happen?
> 5. Creative mode inventory issues are gotcha and in most cases a known wontfix because creative mode players most of the time don’t send enough data to identify what item was picked as what other item. This is probably related to runtime IDs but other than that there is no packet till even after the fact so that’s not something we can easily help with. It’s the same on ProtocolSupport.
>    You may open issue requests for a few of those but some will probably be labeled a wontfix very quickly

1. We need to enable that on a 1.15.2 server? I thought that option was for <1.12.2, ill try that next time!
2. Yeah
3. See above, 1.12.2
4. ^
5. No creative inventory issues with PS but ViaVersion does. Thanks for your time to answer Xernium :)

**Comment by KennyTV** [comment]
The scrambling for the 1.12 client should be fixed now

**Comment by KennyTV** [comment]
Aaaand with the last box checked, we're ready for the major release once 1.16 is out and done 🎉
