### ISSUE TITLE
Console spam errors

### ISSUE THREAD

**Issue by zenandreas** [ViaVersion/ViaBackwards#195]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/6ba8ee58224c2aaabeac49635b131de526c803476d2129dc8870654079b9bcb3

### How/when does this error happen? login?:
> everytime a player with a lower versian that 1.15 is online

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/8c4ksVfi

**Comment by KennyTV** [comment]
The first appearance of the warning tells you why it happens and what you can do.

**Comment by zenandreas** [comment]
I have no idea what that means and what to do, otherwise i wouldn't have it posted here correct?

**Comment by KennyTV** [comment]
"The first appearance", as in you need to scroll up and find the first time the warning appears.
That would have given you these two lines with all you need to know:
`This is very likely caused by a plugin sending a teleport packet for an entity outside of the player's range. You can disable this warning in the ViaVersion config under "suppress-metadata-errors"`
