### ISSUE TITLE
Certain items do not show up in shulker previews on 1.12 and below on 1.13+ servers

### ISSUE THREAD

**Issue by 22s** [ViaVersion/ViaBackwards#223]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on <1.13 on a 1.15.2 viabackwards instance
2. obtain an enchanted golden apple or a mob spawner
3. They cannot be displayed inside shulkers in your inventory and can only be seen when the shulker is placed and opened, this occurs with both mob spawners and with enchanted golden apples.

**Expected behaviour**
they should be listed in the shulkers contents 

**Screenshots**
1.15.2: https://imgur.com/w1FxyjS
1.12.2: https://imgur.com/GX2wPXD
On both versions when the shulker is placed and opened. https://imgur.com/YR9S2sJ

**Additional server info**
No proxy and I am using Akarin 1.15.2 but this can also be found on Paper 1.15.2 and probably Spigot too.

**Comment by 22s** [comment]
edit: turns out the 1.13 -> 1.12 mapping file doesnt include item datavalues as an option for item mapping, this is why things like colored beds, mob spawners, and enchanted golden apples dont get mapped. this also means damaged anvils, banners, colored carpets, charcoal, mossy cobblestone walls, colored concretes, concrete powders, cooked salmon, coarse dirt, podzol, variant plants, dyes, variant fishes, variant leaves blocks, variant logs, all mossy block & infested variants, all variant wood planks, prismarine blocks, chiseled and pillar quartz blocks, red sandstones variants, sandstone variants, saplings, mob and player skulls, wet sponges, stained glass, colored glass panes, terracotta variants, all stone variants, all slab types, stone brick variants, tall grass, ferns, and all wool types wont be rendered correctly within inventories.

**Comment by 22s** [comment]
pls add data values so i can remap everything in the json. i can commit afterwards

**Comment by KennyTV** [comment]
The mappings file does refer to blocks and items with their legacy id, but those are only the new ones eitherway, so they have nothing to do with the (non-)issue.
Have you ever actually opened hovered over a shulker box in 1.12 singleplayer? 👀

**Comment by 22s** [comment]
i have hovered over a shulker box in 1.12 and it's worked just fine. its only a viabackwards issue. protocolsupport doesnt have this issue either. try looking into this bug instead of just closing it and youll realize that its an issue with viabackwards.

**Comment by KennyTV** [comment]
To set a final stance on this: We know that there is _an_ issue, but enchanted apples are just a bad example since sub 1.12 clients just call then "Golden Apple" as well anyways. But more importantly, this sums is up pretty well https://discordapp.com/channels/316206679014244363/316208160232701955/729940748627083275
 and could, in theory, be easily abused to make the server do a lot of work in conversion. So it is both a non-issue (because eh, who cares about the few lines of text) and not really worthwhile in the first place.

**Comment by 22s** [comment]
i can write all the conversions, i have a playerbase highly dependent on 1.12 stability. if theres a way to make data value items be visible i can provide mapping.

**Comment by KennyTV** [comment]
Again, this has absolutely nothing to do with mappings. This has to do with us not processing a shulker's item data _at all_ because of the reasons mentioned above, as well as in the Discord support channel. Sorry, but this is a won't fix, because it's 5 lines of hover text, of which a fix would open your server up for a lot of **really** enduring processing - so it is just not worth the penalty.

If you think that you still want it, you can pay someone else to implement the item nbt list processing for you, but this is definitely not something that will go into the public plugin.
