### ISSUE TITLE
Publishing to Modrinth

### ISSUE THREAD

**Issue by filips123** [ViaVersion/ViaBackwards#567]
### Problem Description

ViaBackwards and ViaRewind are currently not published to Modrinth.

### Solution Description

ViaBackwards and ViaRewind (and other missing Via mods/plugins) should also be published to Modrinth. This is already the case with ViaFabric, ViaFabricPlus and ViaForge. Considering that Modrinth also supports plugins, it might also be useful to publish plugin versions (ViaVersion).

**Comment by Kichura** [comment]
I did have a talk about viabackwards and viarewind being published to modrinth one day instead of just curseforge but kenny decided not to go for it due to it being yikes to him and instead considered asking people to use hangar instead for obtaining such builds, *(jenkins included for latest CI builds)*

In short, it's unlikely that this would be ever done but should it become a thing then this can be reopened but for time being; Hangar is suggested instead.
