### ISSUE TITLE
Add option to load different resource packs on different versions

### ISSUE THREAD

**Issue by bangetto** [ViaVersion/ViaBackwards#727]
### Problem Description

You can only have one resource pack on the server, so assets needed to support older/newer clients have to be loaded for everybody slowing down loading times

### Solution Description

add an option to specify different resource packs for different versions

### Additional Info

it could be made that not all versions need the resource pack, and only specific ones needed

**Comment by kennytv** [comment]
That's generally out of scope for VB, otherwise it would have to become a full-fledged resource pack plugin. Though it's easy to do when getting the client version through API, like https://www.spigotmc.org/resources/perversionresources.74360/. Other plugins also already do that with just an optional dependency
