### ISSUE TITLE
why does viabackwards need a seperate codebase to viaversion

### ISSUE THREAD

**Issue by SergioK29** [ViaVersion/ViaBackwards#879]
why not just run the viaversion converters backwards?

**Comment by kennytv** [comment]
Because it's more complicated than that

**Comment by FlorianMichael** [comment]
You cannot run the code just backwards as it will expect different data/behaviour;

For example `ViaVersions 1.8->1.9` protocol allows `1.9 clients` on a `1.8 server`, and will therefore:
- read `1.8 clientbound packets` sent by the server and transform them to `1.9 packets` for the `client`
- read `1.9 serverbound packets` sent by the client and transform them to `1.8 packets` for the `server`

ViaBackwards/ViaRewind needs to do the `exact opposite` where you can't just run ViaVersion's code again since it's only built for this one direction (`1.9 client on 1.8 server`).
